// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeilolqxvvwldvwvkjha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlaWxvbHF4dnZ3bGR2d3ZramhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTM4MDIsImV4cCI6MjA2NDA4OTgwMn0.17mmuuJ0UUvGnqyMvSatz-1vtirPWsovEIM5psvIQgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);